### ISSUE TITLE
Might be beneficial to make a build from edges method in your graph class

### ISSUE THREAD

**Issue by anton-perez** [snowthesprite/graph#2]
You should create a self.nodes attribute that includes each node and a build from edges method that connects each node to each other within that nodes attribute instead of trying to do it all in your depth and breadth methods.

**Comment by snowthesprite** [comment]
It ended up happening and took a long while. It was fate, for me to spend an hour reluctantly rewriting all my code because I thought I could do it just fine without a self.nodes.
