### ISSUE TITLE
calc_shortest_path for weighted_graph

### ISSUE THREAD

**Issue by RavenHex1296** [snowthesprite/graph#5]
instead of doing for pair in self.edges and assigned a and b to pair[0] and pair[1], respectively, you can actually just do for (a, b) in self.edges and then directly do your if statement. It'll output the same thing but saves you 2 lines.

**Comment by snowthesprite** [comment]
Oh nice. I remember that, but not at the time lemme fix it

**Comment by snowthesprite** [comment]
Man I shouldn't close these when I forget to do them
